### ISSUE TITLE
 Cannot read property 'nodeName' of null - info.plist ipa file

### ISSUE THREAD

**Issue by nvcken** [TooTallNate/plist.js#55]
I use this lib to read info.plist of ipa file.
I got this error
```
TypeError: Cannot read property 'nodeName' of null
    at Object.parse (d:\Appota\appota_flight\node_modules\plist\lib\parse.js:45:26)
    at Object.exports.install [as handle] (d:\Appota\appota_flight\routes\upbuild.js:241:2
5)
    at next_layer (d:\Appota\appota_flight\node_modules\express\lib\router\route.js:103:13
)
    at Route.dispatch (d:\Appota\appota_flight\node_modules\express\lib\router\route.js:10
7:5)
    at d:\Appota\appota_flight\node_modules\express\lib\router\index.js:205:24
    at param (d:\Appota\appota_flight\node_modules\express\lib\router\index.js:286:14)
    at param (d:\Appota\appota_flight\node_modules\express\lib\router\index.js:298:16)
    at Function.proto.process_params (d:\Appota\appota_flight\node_modules\express\lib\rou
ter\index.js:314:3)
    at next (d:\Appota\appota_flight\node_modules\express\lib\router\index.js:199:19)
    at next (d:\Appota\appota_flight\node_modules\express\lib\router\index.js:176:38)
GET /ins/1415257358528 200 120001ms
 req install
TypeError: Cannot read property 'nodeName' of null
    at Object.parse (d:\Appota\appota_flight\node_modules\plist\lib\parse.js:45:26)
    at Object.exports.install [as handle] (d:\Appota\appota_flight\routes\upbuild.js:241:2
5)
    at next_layer (d:\Appota\appota_flight\node_modules\express\lib\router\route.js:103:13
)
    at Route.dispatch (d:\Appota\appota_flight\node_modules\express\lib\router\route.js:10
7:5)
    at d:\Appota\appota_flight\node_modules\express\lib\router\index.js:205:24
    at param (d:\Appota\appota_flight\node_modules\express\lib\router\index.js:286:14)
    at param (d:\Appota\appota_flight\node_modules\express\lib\router\index.js:298:16)
    at Function.proto.process_params (d:\Appota\appota_flight\node_modules\express\lib\rou
ter\index.js:314:3)
    at next (d:\Appota\appota_flight\node_modules\express\lib\router\index.js:199:19)
    at next (d:\Appota\appota_flight\node_modules\express\lib\router\index.js:176:38)
```

**Comment by SchulzKai** [comment]
I ran into the same error.
@nvcken - Did you figure out a way to fix it yet?

**Comment by nvcken** [comment]
@SchulzKai 
Hi , I have not find out yet, I have use other module simple-plist

**Comment by przemyslawpluta** [comment]
Same issue here.

**Comment by fizker** [comment]
I found a strong correlation. I get the exact same error for a binary plist, but the same plist as XML parses fine.

The short term solution would be to convert the binary plist to either XML or JSON by use of objc or swift.  

As Swift:

```swift
import Foundation
let d=NSDictionary(contentsOfFile:"binary.plist")!
if outputAsPlist {
  d.writeToFile("non-binary.plist", atomically:true)
} else {
  let json=NSJSONSerialization.dataWithJSONObject(d, options:.PrettyPrinted, error:nil)
  json?.writeToFile("non-binary.json", atomically:true)
}
```

**Comment by ChristianCiach** [comment]
This still happens with 3.0.0. Can I provide anything to help debugging this issue?

**Comment by everydayfoods** [comment]
still facing the same issue with version 3.1.0
